language: node_js
env:
  - 'DATABASE_URL=postgresql://localhost:5432/fruit'
node_js:
  - 12
before_script:
  - psql -c 'create database fruit;' -U postgres
  - psql -U postgres -d greeting -a -f basket.sql
services:
  - postgresql
